site_name: Project BoxBase
site_description: The open TV Box knowledge database.
site_url: https://coreline.github.io/Project-BoxBase/
repo_url: https://github.com/coreline355/Project-BoxBase
repo_name: coreline355/Project-BoxBase

theme:
  name: material

  language: en

  logo: images/boxbase.svg
  favicon: images/boxbase.png

  palette:

    - scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-night
        name: White Theme

    - scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Dark Theme

  features:

    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

    - search.highlight
    - search.share
    - search.suggest

    - content.code.copy

plugins:
  - search

exclude_docs: includes/**

extra_files:
  - google67c6a94ae3346584.html

markdown_extensions:

  - admonition
  - tables
  - toc:
      permalink: true

  - pymdownx.snippets:
      base_path:
        - docs
        - includes

